plugins { id 'com.android.application' }
android {
    namespace 'com.example.helloworld'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.helloworld"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "2.0"
        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    // Point Gradle to the CMake file
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
